### ISSUE TITLE
Getting error "Problem with the requested skill's response" with 2.24.0 (ask-sdk) version but same is working with 2.0.0

### ISSUE THREAD

**Issue by Kailash2509** [amzn/alexa-skills-kit-java#228]
## I'm submitting a...

<pre><code>[ x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I am creating a new skill, with ask-sdk version 2.0.0 it's invoked properly but when I use 2.24.0 version I am getting the error "There is problem with requested skill's response" in Hindi it's "रिक्वेस्ट की गई स्किल की प्रतिक्रिया में कोई समस्या थी "

## Expected Behavior
It should work same in both 2.24.0 and 2.0.0 versions

## Current Behavior
I get following error in logs when I use 2.24.0 version 

org/apache/logging/log4j/util/ReflectionUtil: java.lang.**NoClassDefFoundError**
java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/ReflectionUtil
at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:42)
at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
at com.amazon.ask.request.dispatcher.impl.BaseRequestDispatcher.<clinit>(BaseRequestDispatcher.java:50)
at com.amazon.ask.CustomSkill.<init>(CustomSkill.java:54)
at com.amazon.ask.Skill.<init>(Skill.java:29)
at com.amazon.ask.builder.StandardSkillBuilder.build(StandardSkillBuilder.java:69)
at com.mydost.streamhandler.**MyDostStreamHandler**.getSkill(MyDostStreamHandler.java:12)
at com.mydost.streamhandler.****MyDostStreamHandler**.<init>(**MyDostStreamHandler.java:16)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.util.ReflectionUtil
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

## Steps to Reproduce (for bugs)
 Invoke the new skill have put 2.24.0 ask-sdk version in pom.xml file
Follwing is the code : -

`public class **MyDostStreamHandler** extends SkillStreamHandler {

	private static Skill getSkill() {
		
		return Skills.standard().addRequestHandlers(new LaunchRequestHandler()).build();
	}

	public MyDostStreamHandler() {
		super(getSkill());
	}
}`

`public class LaunchRequestHandler  implements RequestHandler{

	@Override
	public boolean canHandle(HandlerInput input) {
	return input.matches(requestType(LaunchRequest.class));

	}

	@Override
	public Optional<Response> handle(HandlerInput input) {

	  String speechText = "test response ";

		return input.getResponseBuilder().withSpeech(speechText)
				.withShouldEndSession(true).build();
	}

}
`

The same code above works with 2.0.0 but not 2.24.0

## Possible Solution
```

```

## Context
I am trying make a new kill

## Your Environment

* ASK Java SDK version used: 2.24.0
Windows 10 
I am trying to make a Hindi skill but I think it doesn't matter problem with reproduce in English language also

## Java Info

Java 1.8

**Comment by breedloj** [comment]
Hey Kailash,

Thanks for reaching out. I have a couple of questions to help get to the bottom of your issue. Is this the first time you've attempted upgrading your SDK version since the original 2.0.0 release? Also, do you mind attaching your skill pom.xml file, or at least the dependencies section?

From the error log you've provided it looks like this failure is being caused by an internal Log4j dependency error. I am not getting this issue on a fresh sample skill with 2.24.0 but it's possible one of your other dependencies is bringing in a conflicting Log4j dependency. The internal Slf4j logging facade did get updated to work with Log4j2 since the original 2.0.0 release. See #129 

Since this change I have not heard reports of it breaking anyone. However it may have caused unintentional runtime changes if a Log4j 1.x runtime is still on your classpath and 2.x is expected.

**Comment by Kailash2509** [comment]
Hi,
Thanks for reply, It's for the first time, I am writing this skill, I have attached the pom file.
Yes, I am using some logging api's. It would be great if you could tell me which version of logging api's I should use.

Thanks 
Kailash


[pom.zip](https://github.com/alexa/alexa-skills-kit-sdk-for-java/files/3798662/pom.zip)

**Comment by breedloj** [comment]
Thanks for providing the pom. I am able to repro this in my own skill using the dependencies you provided. It appears, from [this StackOverflow post](https://stackoverflow.com/questions/52700803/im-getting-noclassdeffounderror-org-apache-logging-log4j-util-reflectionutil), newer Log4j2 runtimes don't play nicely matched with older Log4j2 dependencies on the same classpath. The SDK itself brings in version 2.8.2 of the log4j2 over Slf4j API dependency this is why you're getting conflicts. You can either change your two Log4j dependencies to use version 2.8.2, or drop them entirely from your pom since the SDK's dependency should be pulling these in for you anyway.

**Comment by breedloj** [comment]
As an aside, I'll do some research in to whether we can safely update our Log4j2 dependency since it's quite out of date or if that'd be breaking to existing users.

**Comment by breedloj** [comment]
With further testing I can amend my previous comment. I'd suggest dropping both explicit log4j dependencies from your pom (log4j-core and log4j-api) and falling back to those the SDK brings along. Since we are not using the Log4j2 API directly (rather, the SLF4J API over a Log4j2 implementation), bringing in the explicit log4j-api dependency will cause logging errors. After I removed those two dependencies from your pom I am able to successfully execute the skill and get logs.

**Comment by Kailash2509** [comment]
Hi,
Thanks for your reply, I will dropp both the explicit log4j dependencies and develop the skill,

Thanks
Kailash
